server:
  port: 8090

spring:
  application:
    name: mapstruct-implicit-mapping

    data-time-format: yyyy-MM-dd'T'HH:mm:ss

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/map-struct_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

